### ISSUE TITLE
Basic Convert to Typescript and ensure build / distribution webpack

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#2]
## I'm submitting a ...  
[x] feature request  

## ...about   
[x] Razor templating  
[x] JS development  

## Current behavior 
it's js, and building is with gulp

## Expected behavior 
it's all typescript, and building / copying is with webpack

## Steps ca.
* [x] rename all files to .ts
* [x] implement webpack building
* [x] implement webpack auto-copying to the correct target
* [x] check if it still runs after building   
note: if it fails, it's probably because the files aren't added in A-Z order
* [x] later: ensure that font-files are not renamed

**Comment by tvatavuk** [comment]
inpage.min.js works without errors with in test http://2sxc.me/
