### ISSUE TITLE
Try to compile eav-core for dual-target (.net 451 / .net standard 2) - 1d

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#26]

**Comment by tvatavuk** [comment]
Each build is in own subfolder, depending on target framework.

![image](https://user-images.githubusercontent.com/2724850/40066650-e990ede6-5864-11e8-86f4-33fe93076167.png)

![image](https://user-images.githubusercontent.com/2724850/40066737-1072f60c-5865-11e8-9abf-f97f5ec25726.png)

**Comment by tvatavuk** [comment]
Test build code is in feature branch **feature/i26_compile_eav-core_for_dual-target**
https://github.com/2sic/eav-server/tree/feature/i26_compile_eav-core_for_dual-target

**Comment by iJungleboy** [comment]
also check for side-effect of changing [ScriptIgnore] with the [jsonsoft-thingy] in the .data/app.xml. Probably none

**Comment by tvatavuk** [comment]
Tested that there is no side-effects in .data/app.xml.
Will merge feature branch to develop.

**Comment by tvatavuk** [comment]
Feature branch feature/i26_compile_eav-core_for_dual-targe merged to develop branch.
Closing this issue.
