### ISSUE TITLE
Webpack bundle css files and sometimes ends with unexpected JS code in inpage.css or inapge.min.css or related map files - 2h

### ISSUE THREAD

**Issue by tvatavuk** [2sic/2sxc-inpage#27]
## I'm submitting a ...  

[x] bug report => search github for a similar issue before submitting  

## ...about   

[x] other / unknown

## Current behavior 

Webpack bundle css files and sometimes ends with unexpected JS code in inpage.css or inapge.min.css or related map files, without obvious error or reason.

## Expected behavior 

No JS code in inpage.css or inapge.min.css files

## Minimal reproduction of the problem with instructions 

run webpack
check inpage.css or inapge.min.css for JS code in it, because it is looks that we get JS code randomly there
This is start of invalid **inpage.css** file that has JS code in it...
```javascript
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
...
``` 
https://gist.github.com/tvatavuk/aaeea05a105b0e52fa60bc9e445cf2d6

## What is the motivation / use case for changing the behavior? 

This issue is causing frustration and lost time because we have to manually check each css and css.map file after each webpack build, and currently we have unreliable build process.
 
Looking similar problem is reported in this Issue on webpack-contrib/extract-text-webpack-plugin
* https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/762
 
It looks like u bug in ETWP :--( so probably have to find alternative solution without it.
 
In Issue “The Future of this Plugin vs. Mini CSS Extract Plugin (=> Use Mini CSS Extract Plugin)” it become clear that we have to move to Mini CSS Extract Plugin if we plan to upgrade to webpac4 (currently we are using webpack3 for 2sxc-inpage)
* https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749

## Steps to implement

* [ ] upgrade to webpack4
* [ ] upgrade webpack plugins to last version that works on webpack4
* [ ] migrate ETWP to mini CSS Extract Plugin in hope that will solve the problem we have

## Anything you would like to add

Estimate: 2h

**Comment by iJungleboy** [comment]
@tvatavuk is this still an issue, or can we close?

**Comment by tvatavuk** [comment]
I didn't see this problem since I created this issue, so let's close it :-)
Webpack3 to Webpack4 upgrade can wait.
