### ISSUE TITLE
Enable paste-from-clipboard only on if feature enabled (2h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#35]
## I'm submitting a ...  
[x] feature request  

## ...about   
[x] edit experience / UI  

## Current behavior 
Paste image from clipboard is almost ready. 

## Expected behavior 
I created a feature-management system https://github.com/2sic/2sxc/issues/1527

Basically there is a service which can return a promise to tell you if a feature is enabled or not. Here's the code-snippet how the check will work:

```
    featuresSvc.enabled('f6b8d6da-4744-453b-9543-0de499aa2352').then(
      function(enabled) {
        console.log('async: ' + enabled);
      });
```
The guid you see there is the guid for past-image-from-clipboard. Please use that as a reference. 

Note that to test this, you'll need the newest build of 2sxc & eav, + you'll have add a json-file to your `.databeta/configurations` folder in 2sxc - see attachment. 

## Steps to implement
* [x] get latest 2sxc/eav etc.
* [x] add featuresSvc to where you need it in angularjs
* [x] get the feature to enable/disable based on this...
* [x] but make sure you don't prevent loading of other things just because you're waiting for the promise
* [x] test with the configurations json and without (you need to restart DNN for these tests, as it's cached in memory once loaded)

**Comment by tvatavuk** [comment]
This is still part of feature branch https://github.com/2sic/2sxc-ui/tree/feature/paste-image-from-clipboard because I have to finish removing dependency from jQuery
