### ISSUE TITLE
Create fingerprint provider (1-2h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#36]
https://github.com/2sic/2sxc/blob/develop/2sxc%20Dnn/Environment/Dnn7/FingerprintProvider.cs

use in a razor

```
@ToSic.Eav.Configuration.Fingerprint.System
```

**Comment by tvatavuk** [comment]
This is done, but I have to take a care of issue numbers in comments in future, bacuse this is different repo.
