### ISSUE TITLE
Implement app-management ui / call etc.

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#37]
Mostly about

/src/sxc-admin/apps-management/...

Notes
* [x] always make sure the origin is 2sxc.org - could be http or https, and could have a subdomain, but the origin must come from 2sxc.org

**Comment by tvatavuk** [comment]
need more guidance for vm.featuresCallback in apps-controller.js

**Comment by iJungleboy** [comment]
Some more details

I created a test-button for you, which sends the code outside of hte iframe a message:

![image](https://user-images.githubusercontent.com/5321186/39032701-f7d06ab2-446e-11e8-9371-588d2a7103a3.png)

When you click, you'll see this in the console:

![image](https://user-images.githubusercontent.com/5321186/39032712-0710c7ce-446f-11e8-8ac1-fd7fc2fb7d06.png)

In the JS, it's trying to send you a postMessage

```
  function sendMessage(message) {
    console.log('will send message', message);
    var parent = window.parent;
    if (parent !== window) {
      parent.postMessage(message, '*');
    } else {
      console.warn('wanted to send message to upper window, but can\'t find opener window');
    }
    console.log('send message complete');
  }
```

So your iframe-opener must attach to it, to receive the messages and handle them. 

wanna do a quick telco? I'm free till 08:30

**Comment by tvatavuk** [comment]
Thx, this is great! 
Confirming that vm.featuresCallback is receiving message in from test button in iframe.
Working to finish this part.

**Comment by iJungleboy** [comment]
fyi: Just enhanced the design of the table / tabs / icons and i18n implementation.

**Comment by iJungleboy** [comment]
it doesn't quite work yet. sometimes it gets the url from the local server, but then doesn't show the iframe. I assume you did something wrong with the promise.

**Comment by tvatavuk** [comment]
Part of code that shows iframe is updated and consistently show iframe on each click. 
Added small spinner in case that user need to wait on content from iframe (it is very rare).

**Comment by iJungleboy** [comment]
Minor issue: I can't make the external dialog go away any more. If I click the "manage" again, it should show me the original table again.
