### ISSUE TITLE
Implement server side for features management

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#38]
mostly about

2sxc Dnn WebApi > SystemController > ...

**Comment by tvatavuk** [comment]
Completed, except:
- ensure signature is valid
Can not test:
- SaveFeatures

**Comment by iJungleboy** [comment]
Question: why did you re-cast the feature into another object which looks the same? I wouldn't do that.

**Comment by tvatavuk** [comment]
Yes, this was unnecessary. It is removed.
