### ISSUE TITLE
Create special JWT handler and simple test JS to use it (4-8h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#47]
## I'm submitting a ...  
[x] story  

## ...about   
[x] not 2sxc - this is just here for task management

Real Task: https://github.com/azing-org/azing.Dnn.AuthServices.Jwt/issues/1

**Comment by tvatavuk** [comment]
WIP, have working modification of Dnn.AuthServices.Jwt handler installed on dnn 9.2.0 that has user guid as additional claim with in accessToken.
Created simple jquery test to get user guid in javascript in browser.

![image](https://user-images.githubusercontent.com/2724850/39637694-1725e814-4fc4-11e8-8edc-12a29042b54a.png)

TODO:
- package azing.Dnn.AuthServices.Jwt as new handler that can be installed on DNN in addition to core one Dnn.AuthServices.Jwt
- eventually create better automated dnn integration test in JS for this case
