### ISSUE TITLE
Paste image still uploads file when I cancel (quick .25h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#51]
## I'm submitting a ...  
[x] bug report => search github for a similar issue before submitting  

## ...about   
[x] edit experience / UI  

## Current behavior 
if I paste an image and then cancel the name-dialog, it still uploads it. 

## Expected behavior 
cancel should mean no upload

**Comment by tvatavuk** [comment]
fixed issue with Cancel but after Cancel I get blue tinymce dialog "Please use Ctrl+V/Cmd+V keyboard shortcuts to paste contents" :-(
![image](https://user-images.githubusercontent.com/2724850/39709287-c96e293a-5219-11e8-820f-8b2c26d6e3b8.png)

**Comment by iJungleboy** [comment]
you could just virtual-paste an empty text instead - so paste a ""

**Comment by iJungleboy** [comment]
paste empty worked?

**Comment by tvatavuk** [comment]
Moved window.prompt from customEvents to original paste event, where in case of Cancel event.stopImmediatePropagation() is called and that skips blue popup. 
Also this gives me some ideas how to try to avoid blue popup in case of normal pasteImage when user click OK.
