### ISSUE TITLE
implement install same app multiple times #1544 (ca. 2-4h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#53]
https://github.com/2sic/2sxc/issues/1554

Steps probably

* [x] update UI to receive an error, and if it's the right error, show "This app has already been installed. Would you like to install it using another name? and an input field for that (stay in the main dialog all the time, so you can re-submit the file again
* [x] send the file and the new input field (if the user typed in something
* [x] implement the server so it will place the new name in the XML after unzipping but before installing, and then run the standard install
* [x] test
* [x] discuss solution w/2dm

**Comment by iJungleboy** [comment]
todo: when resetting the GUID
if OriginalId node is empty, OR it doesn't exist yet, create the node / add value with the previous GUID

**Comment by tvatavuk** [comment]
Handling of OriginalId is done, tested and pushed to develop.
