### ISSUE TITLE
Implement Server Members-API (? h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#56]

**Comment by iJungleboy** [comment]
please keep me posted...

**Comment by tvatavuk** [comment]
WebAPI Commands (draft) are made as 2sxc app with 2 files:
1. api/DnnMembersController.cs contains implementation of 12 WebAPI methods. 
2. _test.cshtml contains trivial JS code to test this WebAPI methods.

When azing-dnn.dnndev.me website is opened in VS2017 as Local IIS Web Site it is possible to develop with in 2sxc app files with full VS2017 intellisense support and it is possible to attach VS2017 debugger and debug c# code with in 2sxc/app/api/*.cs, so productivity and speed of work are OK and better than with usual DNN modules.

Have to finish testing of WebAPI with _test.cshtml.
Planing finish this part today.

**Comment by tvatavuk** [comment]
This is complied.
2sxc app is in develop branch https://github.com/azing-org/azing.Dnn.Members.Api/tree/develop. 
Spent time was with in 1-2 days.

**Comment by tvatavuk** [comment]
_test.cshtml

![image](https://user-images.githubusercontent.com/2724850/40397059-d732f1ae-5e30-11e8-88d2-538e724c1385.png)

**Comment by iJungleboy** [comment]
cool 👍
