### ISSUE TITLE
promise not working in IE 11? (1h)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#58]
pls check bug https://stackoverflow.com/questions/49920008/2sxc-dnn-edit-app-not-working-in-ie-11

**Comment by tvatavuk** [comment]
Problem exists in v9.14LTS.
Problem do not exists in current v9.30 (tested in develop enviroment, didnt try clean install of all). In IE11 Edit option in DNN action menu is working. User can open Edit dialog, do some changes and Save. User changes are preserved and displayed on page after closing edit dialog. There is one minor JS error in AngularJS after but that do not affect saving or workflow.
Also in IE11 in-page toolbar is working without problems.
So it is best if user can install v9.30, or wait v9.31.
Didn't done any fix here.

**Comment by tvatavuk** [comment]
Spent 30 mins on testing.
