### ISSUE TITLE
pls re-check multi-install app

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#63]
I tried to re-install the qr app where it had already been installed, expecting a "rename this". But instead I got this:

![image](https://user-images.githubusercontent.com/5321186/41395866-7d880a64-6faf-11e8-99e1-5d5381f33d29.png)

Could you check / fix?

**Comment by tvatavuk** [comment]
It is working as expected on my side.

I tested on 3 dnn (742, 911, 920) installations with latest version of 2sic_2SexyContent_09.32.00_Install_LTS_RC2.zip and each time it was as expected.


![image](https://user-images.githubusercontent.com/2724850/41410864-1dddd946-6fdb-11e8-9987-a3c9b8bab19e.png)

![image](https://user-images.githubusercontent.com/2724850/41410965-8039a32c-6fdb-11e8-9074-39f992933b34.png)

![image](https://user-images.githubusercontent.com/2724850/41410996-91decd6e-6fdb-11e8-91b0-f9d9487c1924.png)

**Comment by iJungleboy** [comment]
ok, let's close this for now, I can't prioritize it more.
