### ISSUE TITLE
Review do-ability WYSIWYG-Paste with minimal formatting only - ca. 2-3h

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#68]
This is about https://github.com/2sic/2sxc/issues/1502

Pls

* [x] review specs of tiny mce and suggest what we should do
* [x] implement

**Comment by tvatavuk** [comment]
Had some problems to find needed configuration options in official specification, so I fallback to google and other internet resources. After some testing following configuration did the trick when copy & paste formatted text from word documents to get clean html code with main html tags (h1-h6, p, ul, ol, a):
```javascript
                paste_as_text: false,
                paste_enable_default_filters: true,
                paste_create_paragraphs: true,
                paste_create_linebreaks: false,
                paste_force_cleanup_wordpaste: true,
                paste_use_dialog: true,
                paste_auto_cleanup_on_paste: true,
                paste_convert_middot_lists: true,
                paste_convert_headers_to_strong: false,
                paste_remove_spans: true,
                paste_remove_styles: true
```

**Comment by tvatavuk** [comment]
Here is example...

### Ctrl+C in word document 
![image](https://user-images.githubusercontent.com/2724850/41614217-257f871e-73f8-11e8-9baf-45d8f6bca749.png)

### Ctr+V in WYSIWYG
![image](https://user-images.githubusercontent.com/2724850/41614271-55fa3cc2-73f8-11e8-8534-f838137e4a87.png)

### Html code in WYSIWYG
```html
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<p>&nbsp;</p>
<p>Lorem <strong>ipsum</strong> dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est.</p>
<p>Vivamus a <strong>tellus</strong>. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci. Aenean nec lorem.</p>
<p>In porttitor. <strong>Donec</strong> laoreet nonummy augue. Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.</p>
<p>Fusce <em>aliquet</em> pede non pede. Suspendisse dapibus lorem pellentesque magna. Integer nulla. Donec blandit feugiat ligula. Donec hendrerit, felis et imperdiet euismod, purus ipsum pretium metus, in lacinia nulla nisl eget sapien.</p>
<p><em>Donec ut est in lectus consequat consequat</em>. Etiam eget dui. Aliquam erat volutpat. Sed at lorem in nunc porta tristique. Proin nec augue.</p>
<ol>
<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ol>
<p>&nbsp;</p>
<ul>
<li>Bulet 1</li>
<li>Bulet 2</li>
<li>Bulet 3</li>
</ul>
<p>&nbsp;</p>
<p><a href="https://2sxc.org/en/">https://2sxc.org/en/</a></p>
<p><a href="https://www.2sic.com/">https://www.2sic.com/</a></p>
<p>End</p>
<p>&nbsp;</p>
```

**Comment by tvatavuk** [comment]
Spend cca 1.5h

**Comment by iJungleboy** [comment]
This sounds very good - a few questions

1. create line breaks is false - can it detect line breaks and paragrahps? that would be best
1. can it auto "target"="_blank" hyperlinks? that's the default when you add links manuall
1. are there more options, that we're not setting ATM, which may be of interest?

**Comment by iJungleboy** [comment]
Important note: please always make sure your build also works without ?debug=true, because otherwise when I test your work, it only works in debug. 

Could you check my questions above?

**Comment by tvatavuk** [comment]
Sorry, I did testing in Chrome, Firefox, Edge and IE11 but only in debug mode :-(
In future I will take a care that build also works with release versions.

Plase, can you tell me what gulp/webpack/npm scripts/task/configs I need to run to get right release and debug files in dist folders?

**Comment by tvatavuk** [comment]
1. Break detection is working OK :-)

Word
![image](https://user-images.githubusercontent.com/2724850/41651743-92229a58-7481-11e8-998d-3e6ce830de44.png)

WYSIWYG
![image](https://user-images.githubusercontent.com/2724850/41651728-881a3fde-7481-11e8-9231-d8ff3c048786.png)

HTML code
```html
<p>Line first, then break<br /> continue after break.</p>
<p>New passus.</p>
<p>Break1<br /> Break2<br /> Break3</p>
<p>Pasus1</p>
<p>Pasus2</p>
<p>Pasus3</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
```

**Comment by tvatavuk** [comment]
2. is done. Added code to paste_postprocess event that adds target to hyperlinks in case that hostname is different...
```javascript
                paste_postprocess: function (plugin, args) {
                    var anchors = args.node.getElementsByTagName('a');
                    for (var i = 0; i < anchors.length; i++) {
                        if (anchors[i].hostname != window.location.hostname) {
                            anchors[i].setAttribute('target', '_blank');
                        }
                    }
                }
```
Word
![image](https://user-images.githubusercontent.com/2724850/41653972-2b4a31d6-7488-11e8-9467-001900d268d7.png)

Html after paste
```html
<p><a href="https://www.tinymce.com/docs/plugins/paste/" target="_blank" rel="noopener">https://www.tinymce.com/docs/plugins/paste/</a></p>
<p><a href="https://www.tinymce.com/docs-3x/reference/plugins/Plugin3x@paste/" target="_blank" rel="noopener">https://www.tinymce.com/docs-3x/reference/plugins/Plugin3x@paste/</a></p>
<p><a href="/?debug=true">http://2sxc-dnn742.dnndev.me/?debug=true</a></p>
```

**Comment by tvatavuk** [comment]
3. related to more config options, you can check official documentation for paste plugin, but for version 4 I think that some config options are missing, so you can also refer to version 3 where is more config options mentioned...
https://www.tinymce.com/docs/plugins/paste/
https://www.tinymce.com/docs-3x/reference/plugins/Plugin3x@paste/

**Comment by tvatavuk** [comment]
Build in [latest commit](https://github.com/2sic/2sxc-ui/commit/d2399701cb42b168551e46b1f4c3eee15024d196) is tested that is working with and without ?debug=true in url.

**Comment by iJungleboy** [comment]
thx!

**Comment by iJungleboy** [comment]
Minor wish: could you remove the "is local domain" condition? because as of now, all links are default to target-blank. Better change it to "if no target has been defined, set it to blank" - that way if you're copying something that already has a target, it won't replace it - ok?

**Comment by tvatavuk** [comment]
It is done
https://github.com/2sic/2sxc-ui/blob/fe829134fc193895c157dc6b2feb08496cadf791/src/sxc-edit/fields/string/wysiwyg-tinymce/tinymce.config.service.js#L125-L126
