### ISSUE TITLE
Delete command doesn't use context ~2h

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#72]
## I'm submitting a ... 
[x] bug report => search github for a similar issue before submitting  

## ...about   
[x] commands

## Current behavior 
Commands should use the context to perform API calls - but in some cases - like `delete` and probably also others like `publish` it doesn't use the context. So it will do something like

```
    // convert jQuery ajax promise object to ES6 promise
    return new Promise((resolve: any, reject: any) => {
      context.sxc.webApi.delete(`app-content/any/${itemGuid}`, null, null, true)
        .done((data: any, textStatus: string, jqXHR: any) => {
...
```
see https://github.com/2sic/2sxc-inpage/blob/master/src/entity-manipulation/item-commands.ts#L23
which results in the module-id etc. being 1 (instead of the real module id). 

pls fix :)

## Steps to implement
* [x] recreate
* [x] fix
* [x] test

**Comment by tvatavuk** [comment]
Created possible fix but need more testing tomorrow, to reproduce situation with ModuleId=1.
https://github.com/2sic/2sxc-inpage/blob/a0234ff420d416ddf72eef7e0bfb3b9415f3dcd5/src/entity-manipulation/item-commands.ts#L22-L27

**Comment by iJungleboy** [comment]
Just looking at the code I'm guessing it won't work yet - it may also need changes to the webApi call `sxc.webApi` which probably gets some parameters - just guessing though, but please check / test it yourself. 
you can clone some of the azing-code to get/modify context https://github.com/azing-org/site.catalog-app-cshtml/blob/master/assets/edit.js#L11-L16

to test it.

**Comment by tvatavuk** [comment]
To support deleting of some third party entity from other 2sxc app, had to do following:

1) In 2sxc-inpage, [item-comman.cs](https://github.com/2sic/2sxc-inpage/blob/a0234ff420d416ddf72eef7e0bfb3b9415f3dcd5/src/entity-manipulation/item-commands.ts#L22) is updated to explicit fill zoneId and appId from context,

```javascript
    const params: WebApiParams = {
      zoneId: context.app.zoneId,
      appId: context.app.id,
...
    };

    return new Promise((resolve: any, reject: any) => {
      context.sxc.webApi.delete(`app-content/any/${itemGuid}`, params, null, true)
...
```

2) [2sxc WebAPI deleted method](https://github.com/2sic/2sxc/blob/a85742daa9cb389146d85cab0f8b54ef16c97fc9/Sxc%20WebApi/AppContentController.cs#L343), is updated so it can receive AppId and ZoneId in query string part of WebAPI url (http://2sxc-dnn742-p3.dnndev.me/DesktopModules/2sxc/API/app-content/any/fe7500f0-ea56-43c3-ba22-8788804be23f?zoneId=2&appId=3&lang=en-us&cbisentity=false&cbid=566&originalparameters=%5B%7B%22Key%22%3A%22TabId%22%2C%22Value%22%3A%22150%22%7D%2C%7B%22Key%22%3A%22language%22%2C%22Value%22%3A%22en-US%22%7D%5D), and than use that to create AppIdentity in helper method [GetAppIdFromPathOrContext(string appPath, SxcInstance sxcInstance)](https://github.com/2sic/2sxc/blob/a85742daa9cb389146d85cab0f8b54ef16c97fc9/SxcWebApi/AppContentController.cs#L396)

```csharp
        /// <summary>
        /// Retrieve the appId - either based on the parameter, or if missing, use context
        /// Note that this will fail, if both appPath and context are missing
        /// </summary>
        /// <returns></returns>
        private IAppIdentity GetAppIdFromPathOrContext(string appPath, SxcInstance sxcInstance)
        {
            Log.Add($"detect app from query string parameters");
            var allUrlKeyValues = ControllerContext.Request.GetQueryNameValuePairs();
            int zoneIdFromQueryString = -1;
            int.TryParse(allUrlKeyValues.FirstOrDefault(x => x.Key == "zoneId").Value, out zoneIdFromQueryString);
            int appIdFromQueryString = -100;
            int.TryParse(allUrlKeyValues.FirstOrDefault(x => x.Key == "appId").Value, out appIdFromQueryString);
            if (zoneIdFromQueryString != -1 && appIdFromQueryString != -100)
            {
                Log.Add($"query string parameters detected - appId:{appIdFromQueryString}, zoneId:{zoneIdFromQueryString}");
                return new AppIdentity(zoneIdFromQueryString, appIdFromQueryString, Log);
            }

```

TEST CASE:
Blog module in Portal 0 have some BlogPost.
Test 2sxc app in in Portal 3 and have delete command.

```javascript
function testDelete(){

    var entityId = document.getElementById("entityId").value; 
    var entityGuid = document.getElementById("entityGuid").value;
    var entityTitle = document.getElementById("entityTitle").value;
    var appId = document.getElementById("appId").value;
    var zoneId =  document.getElementById("zoneId").value;
    
    var tag = document.getElementById("deletebutton");

    // var context = $2sxc.context(tag);
    var context = getAndReconfigContext(tag, zoneId, appId);

    var params = { 
    };

    var settings = { 
      action: "delete",
      entityId: entityId, 
      entityTitle: entityTitle, 
      entityGuid: entityGuid,
    };

    $2sxc.cms.run(context, settings, params);

  }
  
  // get the current context, then modify it to ensure that 
  // it will work for the specific zone/app
  // also remove languages, as they are not relevant in the real context
  function getAndReconfigContext(tag, zoneId, appId) {
    var context = $2sxc.context(tag);
    
    context.app.zoneId = zoneId;
    context.app.id = appId;
    context.app.allLanguages = [];
    
    return context;//sxc;
  }
```

NOTES:
1. DNN user had to be SuperUser to delete some entity form 2sxc app in other portal.
2. Colud not reproduce situation to get ModuleId=1

**Comment by iJungleboy** [comment]
thx! I'll close for now - if anything pops up, I'll re-open.
