### ISSUE TITLE
Fix three minor issues on login - ca. 1h

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#75]
* [x] https://github.com/azing-org/azing.Js.User/issues/1
* [x] https://github.com/azing-org/azing.Js.User/issues/2
* [x] https://github.com/azing-org/azing.Js.User/issues/3

**Comment by tvatavuk** [comment]
Done in release https://github.com/azing-org/azing.Js.User/releases/tag/v1.0.2
